# Copyright (c) 2026 OpenStorey LLC. All rights reserved.
# Licensed under the AutoYou Source-Available License.
# See LICENSE in the project root for license information.
"""What run_autoyou installs must be what was audited.

Python packages covered by requirements/locked.txt must match one of its
hashes; Node trees install only what package-lock.json pins, with install
scripts off and no fallback to an unpinned ``npm install``.
"""

import subprocess
from pathlib import Path

import pytest

import scripts.bootstrap_autoyou as bootstrap

GOOD = "a" * 64
OTHER = "b" * 64

LOCK_TEXT = f"""#
# This file is autogenerated by pip-compile with Python 3.13
#
fastapi==0.136.3 \\
    --hash=sha256:{GOOD} \\
    --hash=sha256:{"c" * 64}
    # via -r requirements/base.txt
uvicorn[standard]==0.34.0 \\
    --hash=sha256:{"d" * 64}
"""


def _item(name, version, digest, url="https://files.example.test/pkg.whl", **extra):
    return {
        "metadata": {"name": name, "version": version},
        "download_info": {"url": url, "archive_info": {"hashes": {"sha256": digest}}},
        **extra,
    }


@pytest.fixture
def locked(tmp_path):
    lock = tmp_path / "locked.txt"
    lock.write_text(LOCK_TEXT, encoding="utf-8")
    return bootstrap.parse_locked_hashes(lock)


def test_lockfile_hashes_are_parsed_per_package(locked):
    assert locked["fastapi"] == ("0.136.3", {GOOD, "c" * 64})
    assert locked["uvicorn"] == ("0.34.0", {"d" * 64})


def test_locked_package_with_an_audited_hash_is_pinned(locked):
    lines, unlocked, unhashable = bootstrap.plan_verified_install(
        {"install": [_item("FastAPI", "0.136.3", GOOD)]}, locked
    )
    assert lines == [f"fastapi==0.136.3 --hash=sha256:{GOOD}"]
    assert unlocked == [] and unhashable == []


@pytest.mark.parametrize(
    "item",
    [
        _item("fastapi", "0.136.3", OTHER),  # same version, different file
        _item("fastapi", "0.137.0", GOOD),  # unaudited version
    ],
)
def test_locked_package_that_differs_from_the_lock_is_refused(locked, item):
    with pytest.raises(bootstrap.BootstrapError, match="does not match the audited lockfile"):
        bootstrap.plan_verified_install({"install": [item]}, locked)


def test_unlocked_package_is_pinned_to_the_index_hash_and_reported(locked):
    lines, unlocked, _ = bootstrap.plan_verified_install({"install": [_item("stripe", "15.0.0", OTHER)]}, locked)
    assert lines == [f"stripe==15.0.0 --hash=sha256:{OTHER}"]
    assert unlocked == ["stripe==15.0.0"]


def test_vcs_requirements_are_kept_apart_because_they_have_no_hash(locked):
    vcs = {"metadata": {"name": "cognee", "version": "0.1"}, "download_info": {"url": "git+https://example.test/c.git"}}
    lines, _, unhashable = bootstrap.plan_verified_install({"install": [vcs]}, locked)
    assert lines == [] and unhashable == ["git+https://example.test/c.git"]


def test_portaudio_archive_is_pinned_by_default():
    assert len(bootstrap.PORTAUDIO_SHA256_DEFAULT) == 64


def _node_tree(tmp_path: Path) -> Path:
    folder = tmp_path / "node" / "synthetic"
    folder.mkdir(parents=True)
    (folder / "package.json").write_text('{"name": "synthetic"}', encoding="utf-8")
    (folder / "package-lock.json").write_text('{"lockfileVersion": 3}', encoding="utf-8")
    return folder


def test_npm_runs_ci_without_scripts_and_never_falls_back(tmp_path, monkeypatch):
    folder = _node_tree(tmp_path)
    calls = []

    def fake_run(command, **kwargs):
        calls.append(list(command))
        return subprocess.CompletedProcess(command, 1)

    monkeypatch.setattr(bootstrap.subprocess, "run", fake_run)
    monkeypatch.setattr(bootstrap, "node_lock_fingerprint", lambda *_args: "synthetic-fingerprint")
    monkeypatch.setattr(bootstrap, "REPO_ROOT", tmp_path)

    assert bootstrap.install_locked_node_dependencies("npm", "node", folder, env={}) is False
    assert calls == [["npm", "ci", "--ignore-scripts", "--silent", "--no-fund", "--no-audit"]]


def test_npm_skips_a_tree_already_installed_from_the_same_lock(tmp_path, monkeypatch):
    folder = _node_tree(tmp_path)
    (folder / "node_modules").mkdir()
    (folder / "node_modules" / bootstrap.NODE_LOCK_STAMP_NAME).write_text("same\n", encoding="utf-8")
    monkeypatch.setattr(bootstrap, "node_lock_fingerprint", lambda *_args: "same")
    monkeypatch.setattr(bootstrap, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(bootstrap.subprocess, "run", lambda *a, **k: pytest.fail("npm should not run"))

    assert bootstrap.install_locked_node_dependencies("npm", "node", folder, env={}) is True


def test_npm_refuses_a_tree_without_a_lockfile(tmp_path, monkeypatch):
    folder = _node_tree(tmp_path)
    (folder / "package-lock.json").unlink()
    monkeypatch.setattr(bootstrap, "REPO_ROOT", tmp_path)
    monkeypatch.setattr(bootstrap.subprocess, "run", lambda *a, **k: pytest.fail("npm should not run"))

    assert bootstrap.install_locked_node_dependencies("npm", "node", folder, env={}) is False


def test_only_named_install_scripts_run_after_ci(tmp_path, monkeypatch):
    folder = _node_tree(tmp_path)
    calls = []

    def fake_run(command, **kwargs):
        calls.append(list(command))
        if command[1] == "ci":
            (folder / "node_modules" / "puppeteer").mkdir(parents=True)
            (folder / "node_modules" / "puppeteer" / "install.mjs").write_text("", encoding="utf-8")
        return subprocess.CompletedProcess(command, 0)

    monkeypatch.setattr(bootstrap.subprocess, "run", fake_run)
    monkeypatch.setattr(bootstrap, "node_lock_fingerprint", lambda *_args: "fresh")
    monkeypatch.setattr(bootstrap, "REPO_ROOT", tmp_path)

    assert bootstrap.install_locked_node_dependencies(
        "npm", "node", folder, env={}, allowed_install_scripts=(("puppeteer", "install.mjs"),)
    )
    assert calls[1] == ["node", str(folder / "node_modules" / "puppeteer" / "install.mjs")]
    assert (folder / "node_modules" / bootstrap.NODE_LOCK_STAMP_NAME).read_text(encoding="utf-8").strip() == "fresh"
