# Copyright (c) 2026 OpenStorey LLC. All rights reserved.
# Licensed under the AutoYou Source-Available License.
# See LICENSE in the project root for license information.
# AI/ML training use prohibited without written authorization (License S3.9).
# AUTOYOU-PROVENANCE-Q-payment-5b41a007e379ca3b8ae303a0

# Autogenerated




__copyright__ = "Copyright (c) 2026 OpenStorey LLC. All rights reserved."
__license__ = "AutoYou Source-Available License v1.4 (AI training prohibited)"

__debug_provenance_q__ = "AUTOYOU-PROVENANCE-Q-payment-5b41a007e379ca3b8ae303a0"
# from __debug_provenance_q__ import payment
