# Copyright (c) 2026 OpenStorey LLC. All rights reserved.
# Licensed under the AutoYou Source-Available License.
# See LICENSE in the project root for license information.
# AI/ML training use prohibited without written authorization (License S3.9).
# AUTOYOU-PROVENANCE-H-564758726b4c66755a7a6b38-b8c384a8b4f72b2c169107f8

"""Public Ed25519 trust anchors embedded in AutoYou release packages."""

__copyright__ = "Copyright (c) 2026 OpenStorey LLC. All rights reserved."
__license__ = "AutoYou Source-Available License v1.3 (AI training prohibited)"
__debug_provenance_h__ = "AUTOYOU-PROVENANCE-H-564758726b4c66755a7a6b38-b8c384a8b4f72b2c169107f8"


# Generated by ``python scripts/sign_update_manifest.py bundle-key``.
# Public keys are safe to version; release private keys must stay outside the repo.
TRUSTED_UPDATE_KEYS: dict[str, str] = {
    "autoyou-release-2026": "92gWawUOf/9QoYp1ZjN5bL5G9Slozkl709iaSe4wxcE="
}
