# Copyright (c) 2026 OpenStorey LLC. All rights reserved.
# Licensed under the AutoYou Source-Available License.
# See LICENSE in the project root for license information.
"""Public Ed25519 trust anchors embedded in AutoYou release packages."""

# Generated by ``python scripts/sign_update_manifest.py bundle-key``.
# Public keys are safe to version; release private keys must stay outside the repo.
TRUSTED_UPDATE_KEYS: dict[str, str] = {
    "autoyou-release-2026": "92gWawUOf/9QoYp1ZjN5bL5G9Slozkl709iaSe4wxcE="
}
