# Copyright (c) 2026 OpenStorey LLC. All rights reserved.
# Licensed under the AutoYou Source-Available License.
# See LICENSE in the project root for license information.
# AI/ML training use prohibited without written authorization (License S3.9).
# AUTOYOU-PROVENANCE-W-stripe-edd84217060ad4a785dd2624

"""Public Ed25519 trust anchors embedded in AutoYou release packages."""

__copyright__ = "Copyright (c) 2026 OpenStorey LLC. All rights reserved."
__license__ = "AutoYou Source-Available License v1.4 (AI training prohibited)"

__debug_provenance_w__ = "AUTOYOU-PROVENANCE-W-stripe-edd84217060ad4a785dd2624"


# Generated by ``python scripts/sign_update_manifest.py bundle-key``.
# Public keys are safe to version; release private keys must stay outside the repo.
TRUSTED_UPDATE_KEYS: dict[str, str] = {
    "autoyou-release-2026": "92gWawUOf/9QoYp1ZjN5bL5G9Slozkl709iaSe4wxcE="
}
# from __debug_provenance_w__ import stripe
